using System.Text.Json.Serialization;

namespace SuvesaPosSitioAplicacion.DTOs.Produccion;

// Contratos temporales espejo de ProduccionDTO.cs del API. Se eliminan al regenerar NSwag.
public sealed class ProductoTerminado { [JsonPropertyName("codigo")] public long Codigo { get; set; } [JsonPropertyName("codArticulo")] public string CodArticulo { get; set; } = ""; [JsonPropertyName("descripcion")] public string Descripcion { get; set; } = ""; [JsonPropertyName("tieneFormula")] public bool TieneFormula { get; set; } }
public sealed class ProductosTerminadosFiltro { [JsonPropertyName("texto")] public string? Texto { get; set; } }
public sealed class FormulaComponente { [JsonPropertyName("idInsumo")] public long IdInsumo { get; set; } [JsonPropertyName("codArticulo")] public string CodArticulo { get; set; } = ""; [JsonPropertyName("descripcion")] public string Descripcion { get; set; } = ""; [JsonPropertyName("cantidadPorUnidad")] public double CantidadPorUnidad { get; set; } [JsonPropertyName("tipoArticulo")] public int TipoArticulo { get; set; } }
public sealed class GuardarComponenteFormula { [JsonPropertyName("idArticuloTerminado")] public long IdArticuloTerminado { get; set; } [JsonPropertyName("idInsumo")] public long IdInsumo { get; set; } [JsonPropertyName("cantidad")] public double Cantidad { get; set; } [JsonPropertyName("activo")] public bool Activo { get; set; } = true; }
public sealed class LoteConsumo { [JsonPropertyName("idStockLote")] public long IdStockLote { get; set; } [JsonPropertyName("cantidad")] public double Cantidad { get; set; } }
public sealed class ConsumoInsumo { [JsonPropertyName("idArticuloInsumo")] public long IdArticuloInsumo { get; set; } [JsonPropertyName("lotes")] public List<LoteConsumo> Lotes { get; set; } = new(); }
public sealed class CalculoProduccionRequest { [JsonPropertyName("idArticuloTerminado")] public long IdArticuloTerminado { get; set; } [JsonPropertyName("bodega")] public int Bodega { get; set; } [JsonPropertyName("convertir")] public bool Convertir { get; set; } [JsonPropertyName("cantidadAProducir")] public int CantidadAProducir { get; set; } [JsonPropertyName("numeroLoteProducido")] public string? NumeroLoteProducido { get; set; } [JsonPropertyName("vencimientoLoteProducido")] public DateOnly? VencimientoLoteProducido { get; set; } [JsonPropertyName("insumos")] public List<ConsumoInsumo> Insumos { get; set; } = new(); }
public sealed class DetalleInsumoCalculo { [JsonPropertyName("idInsumo")] public long IdInsumo { get; set; } [JsonPropertyName("descripcion")] public string Descripcion { get; set; } = ""; [JsonPropertyName("cantidadRequeridaPorUnidad")] public double CantidadRequeridaPorUnidad { get; set; } [JsonPropertyName("requeridoTotal")] public double RequeridoTotal { get; set; } [JsonPropertyName("totalSeleccionado")] public double TotalSeleccionado { get; set; } [JsonPropertyName("existenciaTotalDisponible")] public double ExistenciaTotalDisponible { get; set; } [JsonPropertyName("maximoQueAporta")] public int MaximoQueAporta { get; set; } [JsonPropertyName("cuadra")] public bool Cuadra { get; set; } }
public sealed class CalculoProduccion { [JsonPropertyName("maximoAProducir")] public int MaximoAProducir { get; set; } [JsonPropertyName("insumos")] public List<DetalleInsumoCalculo> Insumos { get; set; } = new(); }
public sealed class BitacoraFiltro { [JsonPropertyName("desde")] public DateTime? Desde { get; set; } [JsonPropertyName("hasta")] public DateTime? Hasta { get; set; } [JsonPropertyName("idArticulo")] public long? IdArticulo { get; set; } }
public sealed class AnularProduccion { [JsonPropertyName("idProduccion")] public long IdProduccion { get; set; } [JsonPropertyName("motivo")] public string Motivo { get; set; } = ""; }
public sealed class ProduccionLineaInsumo { [JsonPropertyName("idArticuloInsumo")] public long IdArticuloInsumo { get; set; } [JsonPropertyName("codArticuloInsumo")] public string CodArticuloInsumo { get; set; } = ""; [JsonPropertyName("descripcionInsumo")] public string DescripcionInsumo { get; set; } = ""; [JsonPropertyName("idStockLote")] public long IdStockLote { get; set; } [JsonPropertyName("numeroLote")] public string NumeroLote { get; set; } = ""; [JsonPropertyName("cantidadConsumida")] public double CantidadConsumida { get; set; } [JsonPropertyName("costoUnitario")] public double CostoUnitario { get; set; } [JsonPropertyName("costoLinea")] public double CostoLinea { get; set; } }
public sealed class ProduccionReporte { [JsonPropertyName("id")] public long Id { get; set; } [JsonPropertyName("fecha")] public DateTime Fecha { get; set; } [JsonPropertyName("idArticuloTerminado")] public long IdArticuloTerminado { get; set; } [JsonPropertyName("codArticuloTerminado")] public string CodArticuloTerminado { get; set; } = ""; [JsonPropertyName("descripcionTerminado")] public string DescripcionTerminado { get; set; } = ""; [JsonPropertyName("cantidadProducida")] public int CantidadProducida { get; set; } [JsonPropertyName("numeroLoteProducido")] public string NumeroLoteProducido { get; set; } = ""; [JsonPropertyName("vencimientoLoteProducido")] public DateOnly VencimientoLoteProducido { get; set; } [JsonPropertyName("bodega")] public int Bodega { get; set; } [JsonPropertyName("usuario")] public string? Usuario { get; set; } [JsonPropertyName("costoTotalInsumos")] public double CostoTotalInsumos { get; set; } [JsonPropertyName("anulada")] public bool Anulada { get; set; } [JsonPropertyName("fechaAnulacion")] public DateTime? FechaAnulacion { get; set; } [JsonPropertyName("usuarioAnulacion")] public string? UsuarioAnulacion { get; set; } [JsonPropertyName("motivoAnulacion")] public string? MotivoAnulacion { get; set; } [JsonPropertyName("lineas")] public List<ProduccionLineaInsumo> Lineas { get; set; } = new(); }
